language: java
sudo: true
dist: trusty
jdk:
- oraclejdk11
services:
- docker
addons:
  sonarcloud:
    organization: "microservices-demos"
    token:
      secure: 
       - echo "$SONAR_TOKEN" # encrypted value of your token
before_install:
- chmod +x mvnw
- mvn clean
- echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
- docker pull openjdk:8-jdk-alpine
script:
- cp .travis.settings.xml $HOME/.m2/settings.xml
- cat $HOME/.m2/settings.xml
- mvn heroku:deploy
after_success:
- travis_wait mvn site -o
- bash <(curl -s https://codecov.io/bash)
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sandro-lopes_product-spring-boot
- bash <(curl -s https://codecov.io/bash)
