language: java
sudo: true
dist: trusty
jdk:
- openjdk11
services:
- docker
addons:
  apt:
    packages:
      - oracle-java11-installer
  sonarcloud:
    organization: "microservices-demos"
    token:
      secure: 
       - echo "$SONAR_TOKEN" # encrypted value of your token
before_install:
- chmod +x mvnw
- mvn clean
- echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
- docker pull openjdk:11-jdk-alpine
script:
- cp .travis.settings.xml $HOME/.m2/settings.xml
- cat $HOME/.m2/settings.xml
- mvn deploy
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sandro-lopes_product-spring-boot
after_success:
- bash <(curl -s https://codecov.io/bash)