services:
- docker
jobs:
  include:
    - stage: Build
      name: Build
      script:
      - mvn clean package -Dmaven.test.skip=true
    - stage: Tests
      name: Unit Tests
      script: 
      - mvn clean test
    - stage: Tests
      name: Integration Tests
      script: 
      - mvn test-compile failsafe:integration-test
    - stage: QA
      name: SonarCloud
      addons:
        sonarcloud:
          organization: "$SONAR_ORGANIZATION"
          token: "$SONAR_TOKEN"
      script:
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey="$SONAR_PROJECT_KEY"
      - chmod +x ./quality-gate-status.sh
      - ./quality-gate-status.sh
    - stage: Deploy
      name: Docker Hub
      script: 
      - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
      - mvn clean deploy -Dmaven.test.skip=true -Ddocker.image.prefix="$DOCKER_USERNAME"
    - stage: Deploy
      name: Heroku
      script: 
      - mvn heroku:deploy -Dmaven.test.skip=true
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'