language: java
sudo: true
dist: trusty
jdk:
- openjdk8
services:
- docker
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
- chmod +x mvnw
- mvn clean
- echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
- docker pull openjdk:8-jdk-alpine
script:
- cp .travis.settings.xml $HOME/.m2/settings.xml
- cat $HOME/.m2/settings.xml
- mvn deploy
after_success:
- bash <(curl -s https://codecov.io/bash)