spring:
  profiles:
    active: prod
    
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:demo-db
    username: sa

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect     
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: true

  data:
    rest:
      default-page-size: 20
      max-page-size: 100
      detection-strategy: annotated        