#api
spring:
  profiles:
    active: test

# json
  hateoas:
    use-hal-as-default-json-media-type: false

# datasource
  datasource: 
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:demo-db
    username: sa
    password: 

# jpa
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# h2
  h2:
    console:
      enabled: true
      path: /h2-console

# log level
logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: debug
